"""post tags binding

Revision ID: e0e5817862bd
Revises: 2606aeceb496
Create Date: 2026-01-18 04:12:36.186230

"""
from alembic import op
import sqlalchemy as sa


revision = 'e0e5817862bd'
down_revision = '2606aeceb496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_appeals_reviewer_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_appeals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeals'))
    )
    op.create_table('moderation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_moderation_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation_logs')
    op.drop_table('appeals')
    # ### end Alembic commands ###

